{% set name = "sphinxcontrib-matlabdomain" %}
{% set version = "0.20.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinxcontrib-matlabdomain-{{ version }}.tar.gz
  sha256: 35590605cee94213bfe3316776c8a055e1e314fa0b43f278a480c1d7a601846a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools-scm <6.0.0
    - pip
  run:
    - python >=3.8
    - sphinx >=4.0.0
    - pygments >=2.0.1

test:
  imports:
    - sphinxcontrib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sphinx-contrib/matlabdomain
  summary: Sphinx "matlabdomain" extension
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - joeced
